config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('o-mnie', views.AboutMe.as_view(), name='o-mnie'),
    path('kontakt', views.Contact.as_view(), name='kontakt'),
    path('oferta', views.Offer.as_view(), name='oferta'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home/home.html'


class AboutMe(TemplateView):
    template_name = 'home/about_me.html'


class Contact(TemplateView):
    template_name = 'home/contact.html'


class Offer(TemplateView):
    template_name = 'home/offer.html'

home/templates/home/about_me.html
{% extends 'base.html' %}
{% block content %}
    <section class="container my-5">
        <div class="row">
            <div class="col-md-7">
                <h2 class="display-5">O <span class="text-danger">
                    mnie
                </span></h2>
                <p class="lead">Nazywam się Sylwia Mandrysz.</p>
            </div>
            <div class="col-md-5">
                <img src="/static/images/photo_about.jpeg" class="img-fluid shadow" alt="offer">
            </div>
        </div>
    </section>
{% endblock %}

home/templates/home/contact.html
{% extends 'base.html' %}

{% block content %}
    <section class="container my-5">
        <div class="row">
            <div class="col-md-7">
                <h2 class="display-5">Kontakt
                </h2>
                <ul class="my-5 social-info" id="contact">
                    <li class="my-3">
                        <i class="fa-solid fa-envelope" aria-hidden="true"></i>
                        <span class="lead">sylwia.mandrysz.music@gmail.com</span>
                    </li>
                    <li class="my-3">
                        <i class="fa-solid fa-phone" aria-hidden="true"></i>
                        <span class="lead">+48 508621602</span>
                    </li>
                    <li class="my-3">
                        <i class="fa-brands fa-instagram" aria-hidden="true"></i>
                        <span class="lead">@sylwia.mandrysz.music</span>
                    </li>
                    <li class="my-3">
                        <i class="fa-brands fa-square-facebook" aria-hidden="true"></i>
                        <span class="lead">Sylwia Mandrysz - Oprawa Muzyczna Ślubów</span>
                    </li>
                    <li class="my-3">
                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                        <span class="lead">Rybnik</span>
                    </li>
                </ul>
            </div>
            <div class="col-md-5">
                <img src="/static/images/photo_contact.jpeg" class="img-fluid shadow" alt="offer">
            </div>
        </div>
    </section>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}

{% block content %}
    <section class="container-fluid">
        <div class="d-flex bg-img flex-column w-100 justify-content-center">
            <h2 class="display-1 text-center text-white-50" style="font-weight: bolder;">
                Sylwia Mandrysz
            </h2>
            <h5 class="display-5 text-center text-white-50" style="font-weight: bolder;">
                Oprawa Muzyczna Ślubów
            </h5>
            <div class="btn text-center">
            <a type="button" class="btn btn-outline-light w-10 rounded-pill" style="font-weight: bolder;" href="{% url 'home:oferta' %}">Oferta</a>
            </div>
        </div>
    </section>
{% endblock %}

home/templates/home/offer.html
{% extends 'base.html' %}

{% block content %}
    <section class="container my-5" id="offer">
        <div class="row">
            <div class="col-md-7">
                <h3 class="display-5">Oferta <span class="text-primary">
                    Ślubna
                </span></h3>
                <p>Oferuję:</p>
                <li>Śpiew podczas ceremoni kościelnej</li>
                <li>Śpiew podczas pierwszego tańca</li>
            </div>
            <div class="col-md-5">
                <img src="/static/images/photo_offer.jpeg" class="img-fluid shadow" alt="offer">
            </div>
        </div>
    </section>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sylwia Mandrysz</title>
    <link rel="stylesheet" href="{% static 'style/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style/base.css' %}">
    <script src="https://kit.fontawesome.com/3a3534c328.js" crossorigin="anonymous"></script>
    <script src="{% static 'scripts/bootstrap.bundle.min.js' %}" async defer></script>
</head>
<body style="background-color: lightgrey">

{% include 'partials/nav.html' %}

{% block content %}

{% endblock %}

{% include 'partials/footer.html' %}
</body>
</html>

templates/partials/footer.html
<section class="bg-white footer p-3">
    <div class="row p-0">
        <p class="text-center text-black p-0">© Sylwia Mandrysz. All Rights Reserved</p>
    </div>
</section>

templates/partials/nav.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-fluid py-2">
    <a class="navbar-brand" href="#">
        <img src="{% static 'images/photo_nav.png' %}" id="main-logo" alt="">
    </a>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a href="{% url 'home:home' %}" class="nav-link active">Strona główna</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'home:o-mnie' %}" class="nav-link active">O mnie</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'home:oferta' %}" class="nav-link active">Oferta</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'home:kontakt' %}" class="nav-link active">Kontakt</a>
        </li>
          <div class="container-fluid">
            <a class="navbar-brand" href="https://www.facebook.com/SylwiaSzpiechOfficial/">
            <img src="{% static 'images/logo_facebook.svg' %}" id="social-media" alt="">
            </a>
          </div>
          <div class="container-fluid">
            <a class="navbar-brand" href="https://www.instagram.com/sylwia.mandrysz.music/">
            <img src="{% static 'images/logo_instagram.svg' %}" id="social-media" alt="">
            </a>
          </div>
          <div class="container-fluid">
            <a class="navbar-brand" href="https://www.youtube.com/@sylwia.mandrysz-oprawamuzyczna">
            <img src="{% static 'images/logo_youtube.svg' %}" id="social-media" alt="">
            </a>
          </div>
      </ul>
    </div>
  </div>
</nav>